/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateUsuariosRouteImport } from './routes/_private/usuarios'
import { Route as PrivateProtocoloRouteImport } from './routes/_private/protocolo'
import { Route as PrivateIncidenciasRouteImport } from './routes/_private/incidencias'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivateConfiguracionesRouteImport } from './routes/_private/configuraciones'
import { Route as PrivateAvisosRouteImport } from './routes/_private/avisos'
import { Route as PrivateRegistrosIndexRouteImport } from './routes/_private/registros.index'
import { Route as PrivateEmpresasIndexRouteImport } from './routes/_private/empresas.index'
import { Route as PrivateRegistrosNuevoRouteImport } from './routes/_private/registros.nuevo'
import { Route as PrivateEmpresasEmpresaIdRouteImport } from './routes/_private/empresas.$empresaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateUsuariosRoute = PrivateUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProtocoloRoute = PrivateProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateIncidenciasRoute = PrivateIncidenciasRouteImport.update({
  id: '/incidencias',
  path: '/incidencias',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateConfiguracionesRoute = PrivateConfiguracionesRouteImport.update({
  id: '/configuraciones',
  path: '/configuraciones',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateAvisosRoute = PrivateAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateRegistrosIndexRoute = PrivateRegistrosIndexRouteImport.update({
  id: '/registros/',
  path: '/registros/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateEmpresasIndexRoute = PrivateEmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateRegistrosNuevoRoute = PrivateRegistrosNuevoRouteImport.update({
  id: '/registros/nuevo',
  path: '/registros/nuevo',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateEmpresasEmpresaIdRoute =
  PrivateEmpresasEmpresaIdRouteImport.update({
    id: '/empresas/$empresaId',
    path: '/empresas/$empresaId',
    getParentRoute: () => PrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/avisos': typeof PrivateAvisosRoute
  '/configuraciones': typeof PrivateConfiguracionesRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/incidencias': typeof PrivateIncidenciasRoute
  '/protocolo': typeof PrivateProtocoloRoute
  '/usuarios': typeof PrivateUsuariosRoute
  '/empresas/$empresaId': typeof PrivateEmpresasEmpresaIdRoute
  '/registros/nuevo': typeof PrivateRegistrosNuevoRoute
  '/empresas/': typeof PrivateEmpresasIndexRoute
  '/registros/': typeof PrivateRegistrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/avisos': typeof PrivateAvisosRoute
  '/configuraciones': typeof PrivateConfiguracionesRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/incidencias': typeof PrivateIncidenciasRoute
  '/protocolo': typeof PrivateProtocoloRoute
  '/usuarios': typeof PrivateUsuariosRoute
  '/empresas/$empresaId': typeof PrivateEmpresasEmpresaIdRoute
  '/registros/nuevo': typeof PrivateRegistrosNuevoRoute
  '/empresas': typeof PrivateEmpresasIndexRoute
  '/registros': typeof PrivateRegistrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/_private/avisos': typeof PrivateAvisosRoute
  '/_private/configuraciones': typeof PrivateConfiguracionesRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/incidencias': typeof PrivateIncidenciasRoute
  '/_private/protocolo': typeof PrivateProtocoloRoute
  '/_private/usuarios': typeof PrivateUsuariosRoute
  '/_private/empresas/$empresaId': typeof PrivateEmpresasEmpresaIdRoute
  '/_private/registros/nuevo': typeof PrivateRegistrosNuevoRoute
  '/_private/empresas/': typeof PrivateEmpresasIndexRoute
  '/_private/registros/': typeof PrivateRegistrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/avisos'
    | '/configuraciones'
    | '/dashboard'
    | '/incidencias'
    | '/protocolo'
    | '/usuarios'
    | '/empresas/$empresaId'
    | '/registros/nuevo'
    | '/empresas/'
    | '/registros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/avisos'
    | '/configuraciones'
    | '/dashboard'
    | '/incidencias'
    | '/protocolo'
    | '/usuarios'
    | '/empresas/$empresaId'
    | '/registros/nuevo'
    | '/empresas'
    | '/registros'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/login'
    | '/_private/avisos'
    | '/_private/configuraciones'
    | '/_private/dashboard'
    | '/_private/incidencias'
    | '/_private/protocolo'
    | '/_private/usuarios'
    | '/_private/empresas/$empresaId'
    | '/_private/registros/nuevo'
    | '/_private/empresas/'
    | '/_private/registros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/usuarios': {
      id: '/_private/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof PrivateUsuariosRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/protocolo': {
      id: '/_private/protocolo'
      path: '/protocolo'
      fullPath: '/protocolo'
      preLoaderRoute: typeof PrivateProtocoloRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/incidencias': {
      id: '/_private/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof PrivateIncidenciasRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/configuraciones': {
      id: '/_private/configuraciones'
      path: '/configuraciones'
      fullPath: '/configuraciones'
      preLoaderRoute: typeof PrivateConfiguracionesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/avisos': {
      id: '/_private/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof PrivateAvisosRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/registros/': {
      id: '/_private/registros/'
      path: '/registros'
      fullPath: '/registros/'
      preLoaderRoute: typeof PrivateRegistrosIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/empresas/': {
      id: '/_private/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof PrivateEmpresasIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/registros/nuevo': {
      id: '/_private/registros/nuevo'
      path: '/registros/nuevo'
      fullPath: '/registros/nuevo'
      preLoaderRoute: typeof PrivateRegistrosNuevoRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/empresas/$empresaId': {
      id: '/_private/empresas/$empresaId'
      path: '/empresas/$empresaId'
      fullPath: '/empresas/$empresaId'
      preLoaderRoute: typeof PrivateEmpresasEmpresaIdRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateAvisosRoute: typeof PrivateAvisosRoute
  PrivateConfiguracionesRoute: typeof PrivateConfiguracionesRoute
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateIncidenciasRoute: typeof PrivateIncidenciasRoute
  PrivateProtocoloRoute: typeof PrivateProtocoloRoute
  PrivateUsuariosRoute: typeof PrivateUsuariosRoute
  PrivateEmpresasEmpresaIdRoute: typeof PrivateEmpresasEmpresaIdRoute
  PrivateRegistrosNuevoRoute: typeof PrivateRegistrosNuevoRoute
  PrivateEmpresasIndexRoute: typeof PrivateEmpresasIndexRoute
  PrivateRegistrosIndexRoute: typeof PrivateRegistrosIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAvisosRoute: PrivateAvisosRoute,
  PrivateConfiguracionesRoute: PrivateConfiguracionesRoute,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateIncidenciasRoute: PrivateIncidenciasRoute,
  PrivateProtocoloRoute: PrivateProtocoloRoute,
  PrivateUsuariosRoute: PrivateUsuariosRoute,
  PrivateEmpresasEmpresaIdRoute: PrivateEmpresasEmpresaIdRoute,
  PrivateRegistrosNuevoRoute: PrivateRegistrosNuevoRoute,
  PrivateEmpresasIndexRoute: PrivateEmpresasIndexRoute,
  PrivateRegistrosIndexRoute: PrivateRegistrosIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
